from typing import Any, Self

import numpy as np
from numpy.typing import ArrayLike, NDArray

class LabelEncoder:
    classes_: NDArray[Any]
    def fit(self, y: ArrayLike) -> Self: ...
    def fit_transform(self, y: ArrayLike) -> NDArray[np.int64]: ...
    def transform(self, y: ArrayLike) -> NDArray[np.int64]: ...
    def inverse_transform(self, y: ArrayLike) -> NDArray[Any]: ...

class StandardScaler:
    scale_: NDArray[np.float64] | None
    mean_: NDArray[np.float64] | None
    var_: NDArray[np.float64] | None
    n_features_in_: int
    def __init__(self, *, copy: bool = ..., with_mean: bool = ..., with_std: bool = ...) -> None: ...
    def fit(self, X: ArrayLike, y: Any = ..., sample_weight: ArrayLike | None = ...) -> Self: ...
    def transform(self, X: ArrayLike, copy: bool | None = ...) -> NDArray[np.float64]: ...
    def fit_transform(self, X: ArrayLike, y: Any = ..., **fit_params: Any) -> NDArray[np.float64]: ...
    def inverse_transform(self, X: ArrayLike, copy: bool | None = ...) -> NDArray[np.float64]: ...
